In [9]:
from sklearn import preprocessing
import pandas as pd
import numpy as np
X_train = pd.DataFrame(np.arange(-3.,3.))
print(X_train)
scaler = preprocessing.StandardScaler().fit(X_train) # the scaler will now ensure that for any new set of data, use the same mean and scale
print(scaler.mean_)
print(scaler.scale_)
print(scaler.transform(X_train)) # by doing this, the transform w
X_test = pd.DataFrame(np.arange(2.,4.))
print(scaler.transform(X_test))
X_test2 = pd.DataFrame(np.arange(16.,20.))
print(scaler.transform(X_test2))

     0
0 -3.0
1 -2.0
2 -1.0
3  0.0
4  1.0
5  2.0
[-0.5]
[1.70782513]
[[-1.46385011]
 [-0.87831007]
 [-0.29277002]
 [ 0.29277002]
 [ 0.87831007]
 [ 1.46385011]]
[[1.46385011]
 [2.04939015]]
[[ 9.66141072]
 [10.24695077]
 [10.83249081]
 [11.41803085]]


In [10]:
1.70782513 * -1.46385011

-2.5000000044112647

In [12]:
-0.87831007 * -1.46385011

1.2857142925836078